# Generated by Django 6.0.1 on 2026-05-05 10:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Video duration in seconds'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_status',
            field=models.CharField(choices=[('none', 'No Video'), ('pending', 'Upload Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='none', max_length=20),
        ),
        migrations.CreateModel(
            name='VideoUploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_size', models.BigIntegerField(help_text='Total file size in bytes')),
                ('total_chunks', models.PositiveIntegerField(default=0)),
                ('uploaded_chunks', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(default='video/mp4', max_length=50)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('uploading', 'Uploading'), ('finalizing', 'Finalizing'), ('complete', 'Complete'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('temp_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_session', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
