# Generated by Django 6.0.1 on 2026-03-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_comment_id_alter_commentlike_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_short',
            field=models.BooleanField(default=False),
        ),
    ]
