# Generated by Django 6.0.1 on 2026-05-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_duration_post_video_status_videouploadsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video_status',
        ),
        migrations.DeleteModel(
            name='VideoUploadSession',
        ),
    ]
