# Generated by Django 6.0.1 on 2026-05-05 13:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_duration_remove_post_video_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_status',
            field=models.CharField(choices=[('none', 'No Video'), ('pending', 'Uploading'), ('processing', 'Trimming/Adding Music'), ('ready', 'Ready to View'), ('failed', 'Error Processing')], default='none', max_length=20),
        ),
        migrations.CreateModel(
            name='VideoUploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_chunks', models.PositiveIntegerField(default=0)),
                ('uploaded_chunks', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='initiated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload_session', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='VideoEngagement',
        ),
    ]
