# Generated by Django 6.0.1 on 2026-05-12 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
        ('posts', '0005_post_duration_post_video_status_videouploadsession_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_short',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_status',
            field=models.CharField(choices=[('none', 'No Video'), ('pending', 'Uploading'), ('processing', 'Trimming/Adding Music'), ('ready', 'Ready to View'), ('failed', 'Error Processing')], db_index=True, default='none', max_length=20),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', '-created_at'], name='posts_comme_post_id_7929fe_idx'),
        ),
        migrations.AddIndex(
            model_name='hashtag',
            index=models.Index(fields=['name'], name='posts_hasht_name_1acbc9_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['league', '-created_at'], name='posts_post_league__6ffe7f_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='posts_post_author__f8ea20_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_short', 'video_status', '-created_at'], name='posts_post_is_shor_9d6f71_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['post', 'user'], name='posts_postl_post_id_af824a_idx'),
        ),
    ]
