# Generated by Django 6.0.1 on 2026-05-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='welcome_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
