# Generated by Django 5.0.14 on 2026-03-09 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_users', to='leagues.league'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_users', to='leagues.team'),
        ),
        migrations.CreateModel(
            name='FanPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_fans', to='leagues.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_fans', to='leagues.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'league')},
            },
        ),
    ]
