# Generated by Django 6.0.1 on 2026-03-18 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_fanpreference_id_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_Profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
