# Generated by Django 6.0.1 on 2026-03-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
