# Generated by Django 6.0.1 on 2026-04-06 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_alter_league_id_alter_team_id'),
        ('users', '0009_add_account_type_badge_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanpreference',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_fans', to='leagues.team'),
        ),
    ]
