# Generated by Django 5.2.1 on 2026-04-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('leagues', '0003_alter_league_id_alter_team_id'),
        ('users', '0012_user_two_fa_enabled_passwordresetotp_twofactorotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_user_email'),
        ),
    ]
