# Generated by Django 6.0.1 on 2026-05-04 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_two_fa_enabled_passwordresetotp_twofactorotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetotp',
            options={'verbose_name': 'Password Reset OTP'},
        ),
        migrations.AlterModelOptions(
            name='twofactorotp',
            options={'verbose_name': 'Two-Factor OTP'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='two_fa_enabled',
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twofactorotp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='twofactorotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='twofactorotp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='twofactorotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
