# Generated by Django 5.2.1 on 2026-05-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_otpcode_alter_passwordresetotp_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='two_fa_enabled',
        ),
        migrations.AddField(
            model_name='profile',
            name='two_fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_otp_failed', 'Login OTP Failed'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset_otp_verified', 'Password Reset OTP Verified'), ('password_reset_completed', 'Password Reset Completed'), ('email_verified_via_otp', 'Email Verified via OTP'), ('logout', 'Logout'), ('register', 'User Registration'), ('google_signin', 'Google Sign-In')], max_length=50),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
