# Generated by Django 5.2.1 on 2026-04-30 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_follow_options_alter_passwordresetotp_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_info', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('otp_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Login History',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='device_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_otp_failed', 'Login OTP Failed'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset_otp_verified', 'Password Reset OTP Verified'), ('password_reset_success', 'Password Reset Success'), ('logout', 'Logout'), ('register', 'User Registration'), ('google_signin', 'Google Sign-In')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'action'], name='users_audit_user_id_c6aa5b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='users_audit_created_6518da_idx'),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
