# Generated by Django 6.0.1 on 2026-05-05 12:52

import django.db.models.deletion
import django.utils.timezone
import short_videos.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
        ('short_videos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('twitter', 'Twitter / X'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('copy_link', 'Copy Link'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_time', models.FloatField(default=0.0, help_text='Seconds watched.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='shortvideo',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='shortvideo',
            name='cached_comments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shortvideo',
            name='cached_likes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='shortvideo',
            name='cached_shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shortvideo',
            name='cached_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shortvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='shorts/thumbnails/'),
        ),
        migrations.AddField(
            model_name='shortvideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shortvideo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shortvideo',
            name='caption',
            field=models.TextField(blank=True, max_length=2200),
        ),
        migrations.AlterField(
            model_name='shortvideo',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shortvideo',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Video duration in seconds (0 – 7200).'),
        ),
        migrations.AlterField(
            model_name='shortvideo',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='short_videos', to='leagues.league'),
        ),
        migrations.AlterField(
            model_name='shortvideo',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='short_videos', to='leagues.team'),
        ),
        migrations.AlterField(
            model_name='shortvideo',
            name='video',
            field=models.FileField(upload_to=short_videos.models.short_video_upload_path),
        ),
        migrations.AddIndex(
            model_name='shortvideo',
            index=models.Index(fields=['league', '-created_at'], name='short_video_league__882481_idx'),
        ),
        migrations.AddIndex(
            model_name='shortvideo',
            index=models.Index(fields=['team', '-created_at'], name='short_video_team_id_f2fb9f_idx'),
        ),
        migrations.AddIndex(
            model_name='shortvideo',
            index=models.Index(fields=['author', '-created_at'], name='short_video_author__35f547_idx'),
        ),
        migrations.AddField(
            model_name='commentmention',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentioned_in_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='comment_mentions', through='short_videos.CommentMention', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='short_videos.videocomment'),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='short_videos.shortvideo'),
        ),
        migrations.AddField(
            model_name='commentmention',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='short_videos.videocomment'),
        ),
        migrations.AddField(
            model_name='videolike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videolike',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='short_videos.shortvideo'),
        ),
        migrations.AddField(
            model_name='videoshare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videoshare',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='short_videos.shortvideo'),
        ),
        migrations.AddField(
            model_name='videoview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videoview',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='short_videos.shortvideo'),
        ),
        migrations.AddIndex(
            model_name='videocomment',
            index=models.Index(fields=['video', 'created_at'], name='short_video_video_i_74f000_idx'),
        ),
        migrations.AddIndex(
            model_name='videocomment',
            index=models.Index(fields=['parent'], name='short_video_parent__580b9c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commentmention',
            unique_together={('comment', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='videolike',
            unique_together={('user', 'video')},
        ),
        migrations.AddIndex(
            model_name='videoview',
            index=models.Index(fields=['video', 'created_at'], name='short_video_video_i_e2ce26_idx'),
        ),
        migrations.AddIndex(
            model_name='videoview',
            index=models.Index(fields=['user', 'created_at'], name='short_video_user_id_fdbb62_idx'),
        ),
    ]
