# Generated by Django 6.0.1 on 2026-05-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_videos', '0003_commentmention_videocomment_videolike_videoshare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoview',
            name='completed',
            field=models.BooleanField(default=False, help_text='True if watch_time >= 90% of video duration.'),
        ),
    ]
