# Generated by Django 6.0.1 on 2026-05-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_videos', '0006_fix_videocomment_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoshare',
            name='platform',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('twitter', 'Twitter / X'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('copy_link', 'Copy Link'), ('reshare', 'In-App Reshare'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
