# Generated by Django 6.0.1 on 2026-03-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('repost', 'Repost'), ('follow', 'Follow'), ('mention', 'Mention')], max_length=20),
        ),
    ]
